# Generated by Django 2.0 on 2020-03-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_movie_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Film',
        ),
        migrations.RemoveField(
            model_name='car',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
