# Generated by Django 2.0 on 2020-03-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200312_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('pages_start', models.IntegerField(null=True)),
                ('pages_stop', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('booktitle', models.IntegerField(null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('authors', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
