# Generated by Django 2.0 on 2020-03-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200313_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='booktitle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
