# Generated by Django 2.0 on 2020-03-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200313_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='booktitle',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
