# Generated by Django 2.0 on 2020-03-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200313_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='pages_start',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='pages_stop',
        ),
    ]
